[project]
name = "romototo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "click>=8.2.0",
    "lxml>=5.4.0",
    "pyyaml>=6.0.2",
    "requests>=2.32.3",
    "selenium>=4.32.0",
]
